### PR TITLE
 new version of autoprefixer now requires postcss-cli 

### PR DESCRIPTION
**Pull request by myguidingstar-zz**

### CODE REVIEW

**Comment by danielsz** [comment]
Awesome. Thanks!

**Comment by myguidingstar-zz** [comment]
can you help with a new release? thanks

**Comment by danielsz** [comment]
Absolutely!

Unfortunately, I am currently away from my master key (needed to sign the artefact), and https://github.com/boot-clj/boot/issues/255 is holding me back. 
BUT I'm hacking on it, and I think by tomorrow I'll be able to cut a new release. 

I hope you can wait until tomorrow. If not, you can try to install 0.0.3 into your local maven repo.

**Comment by danielsz** [comment]
Hi, I've pushed 0.0.4. Can you please test it, and tell me if everything seems to work like it should? 
Thanks!

**Pull request merged**
