### PR TITLE
Include keyword argument usage

### PR DESCRIPTION
**Pull request by livtanong**

### CODE REVIEW

**Comment by danielsz** [comment]
Keyword argument usage is a feature of Boot tasks. Every Boot task supports multiple ways to pass arguments. Why do you think it is necessary to specify this particular usage?

**Comment by livtanong** [comment]
Just for completeness. Some new users might not be familiar with characteristics common across all boot tasks.

**Comment by danielsz** [comment]
Fair enough. Thank you. (And sorry for taking so long.)

**Comment by livtanong** [comment]
No worries! :)

**Pull request merged**
